services:

  python-example-base:
    build: ./pythonbase
    container_name: python-example-base
    image: python-example-base
    depends_on:
      - linux-example-base

  linux-example-base:
    build:
      context: ./linuxbase
      args:
        TZ: ${TZ:-UTC}
    container_name: linux-example-base
    image: linux-example-base
